# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_gradle.html#sec:configuring_build_with_gradle.properties

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_gradle.html#sec:configuring_build_with_gradle.properties

# Enable parallel builds
org.gradle.parallel=true

# Enable caching
org.gradle.caching=true

# Increase the amount of memory available to the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use AndroidX
android.useAndroidX=true

# Enable KMP Default Hierarchy Template
kotlin.mpp.applyDefaultHierarchyTemplate=true
